### ISSUE TITLE
Load ontologies

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/ld4p-rdf-to-blazegraph#18]
Load the BF2, MADSRDF, and associated ontologies (possibly SKOS and FOAF).

- [x] BF2
- [x] MADSRDF
- [x] SKOS
- [x] FOAF

**Comment by dazza-codes** [comment]
Uploaded some ontologies to the blazegraph-dev data at `/rdf/ontologies`, i.e.
```
[ld4p@sul-ld4p-blazegraph-dev ~]$ ll /rdf/ontologies/
total 3128
-rw-r--r-- 1 ld4p users  430120 Nov 15 16:50 bibframe_2_ManchesterSyntax.omn
-rw-r--r-- 1 ld4p users 1277239 Nov 15 16:48 bibframe.owl
-rw-r--r-- 1 ld4p users  182174 Nov 16 16:14 bibframe.rdf
-rw-r--r-- 1 ld4p users   32759 Dec  2 11:30 mads-ontology-20101119.owl
-rw-r--r-- 1 ld4p users  356710 Nov 17 08:46 MADS-RDF_Documentation.pdf
-rw-r--r-- 1 ld4p users  254311 Nov 16 13:44 madsrdf_relators_ManchesterSyntax.omn
-rw-r--r-- 1 ld4p users  344284 Nov 16 10:32 madsrdf_relators.rdf
-rw-r--r-- 1 ld4p users   69794 Nov 16 15:45 madsrdf_v1.owl
-rw-r--r-- 1 ld4p users   91264 Nov 16 15:57 madsrdf_v1.rdf
-rw-r--r-- 1 ld4p users   91319 Nov 16 15:37 madsrdf_v1_withXMLBase.rdf
```

**Comment by dazza-codes** [comment]
blazegraph-dev failed to load the BF2 ontology into an existing namespace with the Casalini records already loaded in it, i.e.
```
[ld4p@sul-ld4p-blazegraph-dev ~]$ ./ld4p-rdf-to-blazegraph/current/bin/blazegraph_sparql_update.sh http://localhost:8080/blazegraph/namespace/ld4p/sparql /rdf/ontologies/bibframe.rdf
2017-03-27T15:53:28-0700  Uploading /rdf/ontologies/bibframe.rdf into http://localhost:8080/blazegraph/namespace/ld4p/sparql

INSERT-WITH-BODY: baseURI=http://localhost:8080/blazegraph/namespace/ld4p/sparql, Content-Type=application/rdf+xml, context-uri=[]
java.util.concurrent.ExecutionException: org.openrdf.repository.RepositoryException: org.openrdf.sail.SailException: java.lang.RuntimeException: java.lang.InterruptedException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:281)
        at com.bigdata.rdf.sail.webapp.InsertServlet.doPostWithBody(InsertServlet.java:206)
        at com.bigdata.rdf.sail.webapp.InsertServlet.doPost(InsertServlet.java:122)
        at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:308)
        at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancyServlet.java:193)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
```

**Comment by dazza-codes** [comment]
blazegraph-dev can load BF2 into an empty namespace, whether the inference option is enabled or not, e.g.

```
# without inference enabled
[ld4p@sul-ld4p-blazegraph-dev ~]$ ./ld4p-rdf-to-blazegraph/current/bin/blazegraph_sparql_update.sh http://localhost:8080/blazegraph/namespace/ontologies/sparql /rdf/ontologies/bibframe.rdf 
2017-03-30T09:47:25-0700  Uploading /rdf/ontologies/bibframe.rdf into http://localhost:8080/blazegraph/namespace/ontologies/sparql
<?xml version="1.0"?><data modified="2223" milliseconds="1702"/>

# with inference enabled
[ld4p@sul-ld4p-blazegraph-dev ~]$ ./ld4p-rdf-to-blazegraph/current/bin/blazegraph_sparql_update.sh http://localhost:8080/blazegraph/namespace/ontologies_inference/sparql /rdf/ontologies/bibframe.rdf 
2017-03-30T09:47:49-0700  Uploading /rdf/ontologies/bibframe.rdf into http://localhost:8080/blazegraph/namespace/ontologies_inference/sparql
<?xml version="1.0"?><data modified="2223" milliseconds="3150"/>
```

**Comment by dazza-codes** [comment]
blazegraph-dev can load MADSRDF-v1 into a namespace that only contains the BF2 ontology, whether the inference option is enabled or not, e.g.
```
# without inference enabled
[ld4p@sul-ld4p-blazegraph-dev ~]$ ./ld4p-rdf-to-blazegraph/current/bin/blazegraph_sparql_update.sh http://localhost:8080/blazegraph/namespace/ontologies/sparql /rdf/ontologies/madsrdf_v1.rdf 
2017-03-30T09:49:42-0700  Uploading /rdf/ontologies/madsrdf_v1.rdf into http://localhost:8080/blazegraph/namespace/ontologies/sparql
<?xml version="1.0"?><data modified="919" milliseconds="515"/>

# with inference enabled (4x slower)
[ld4p@sul-ld4p-blazegraph-dev ~]$ ./ld4p-rdf-to-blazegraph/current/bin/blazegraph_sparql_update.sh http://localhost:8080/blazegraph/namespace/ontologies_inference/sparql /rdf/ontologies/madsrdf_v1.rdf 
2017-03-30T09:49:29-0700  Uploading /rdf/ontologies/madsrdf_v1.rdf into http://localhost:8080/blazegraph/namespace/ontologies_inference/sparql
<?xml version="1.0"?><data modified="919" milliseconds="2343"/>
```

**Comment by dazza-codes** [comment]
blazegraph-dev can load SKOS into a namespace that contains the BF2 and MADS-RDF ontologies, whether the inference option is enabled or not, e.g.

```
# without inference enabled
[ld4p@sul-ld4p-blazegraph-dev ~]$ ./ld4p-rdf-to-blazegraph/current/bin/blazegraph_sparql_update.sh http://localhost:8080/blazegraph/namespace/ontologies/sparql /rdf/ontologies/skos.rdf 
2017-03-30T09:58:35-0700  Uploading /rdf/ontologies/skos.rdf into http://localhost:8080/blazegraph/namespace/ontologies/sparql
<?xml version="1.0"?><data modified="254" milliseconds="267"/>

# with inference enabled (much slower)
[ld4p@sul-ld4p-blazegraph-dev ~]$ ./ld4p-rdf-to-blazegraph/current/bin/blazegraph_sparql_update.sh http://localhost:8080/blazegraph/namespace/ontologies_inference/sparql /rdf/ontologies/skos.rdf 
2017-03-30T09:58:46-0700  Uploading /rdf/ontologies/skos.rdf into http://localhost:8080/blazegraph/namespace/ontologies_inference/sparql
<?xml version="1.0"?><data modified="254" milliseconds="1253"/>
```

**Comment by dazza-codes** [comment]
blazegraph-dev can load FOAF into a namespace that contains the BF2, MADS-RDF, and SKOS ontologies, whether the inference option is enabled or not, e.g.

```
# without inference enabled
[ld4p@sul-ld4p-blazegraph-dev ~]$ ./ld4p-rdf-to-blazegraph/current/bin/blazegraph_sparql_update.sh http://localhost:8080/blazegraph/namespace/ontologies/sparql /rdf/ontologies/foaf.rdf 
2017-03-30T10:15:53-0700  Uploading /rdf/ontologies/foaf.rdf into http://localhost:8080/blazegraph/namespace/ontologies/sparql
<?xml version="1.0"?><data modified="635" milliseconds="139"/>

# with inference enabled (much slower)
[ld4p@sul-ld4p-blazegraph-dev ~]$ ./ld4p-rdf-to-blazegraph/current/bin/blazegraph_sparql_update.sh http://localhost:8080/blazegraph/namespace/ontologies_inference/sparql /rdf/ontologies/foaf.rdf 
2017-03-30T10:15:42-0700  Uploading /rdf/ontologies/foaf.rdf into http://localhost:8080/blazegraph/namespace/ontologies_inference/sparql
<?xml version="1.0"?><data modified="635" milliseconds="1266"/>
```

**Comment by dazza-codes** [comment]
There are now two namespaces with ontologies loaded:
- `/namespace/ontologies`
- `/namespace/ontologies_inference`
